---
- name: Installing the Apache2 on the Agent1
  become: true
  hosts: Instance2
  tasks:
    - name: install apache2
      apt: name=apache2 state=latest
    - name: start apache2
      service:
          name: apache2
          state: started
          enabled: True
- name: Installing the NGINX on the Agent2
  become: true
  hosts: Instance3
  tasks:
    - name: install nginx
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
          enabled: True
