---
- name: Installing the Apache2 on the Slave1
  become: true
  hosts: Agent1
  tasks:
    - name: install apache2
      apt: name=apache2 state=latest
    - name: start apache2
      service:
          name: apache2
          state: started
          enabled: True
- name: Installing the NGINX on the Slave2
  become: true
  hosts: Agent2
  tasks:
    - name: install nginx
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
          enabled: True
